-- ============================================================
-- ST_STOCK_MASTER 테이블에 코스피 추가 컬럼
-- 실행 필수: advstock 기능 사용 전에 반드시 한번 실행해야 합니다.
-- 이미 컬럼이 있으면 오류가 나지만 무시해도 됩니다.
-- ============================================================

-- 안전 실행 (프로시저 방식: 컬럼 존재시 skip)
USE SECKIMDB;

DROP PROCEDURE IF EXISTS add_advstock_columns;

DELIMITER //
CREATE PROCEDURE add_advstock_columns()
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ST_STOCK_MASTER' AND COLUMN_NAME = 'SECTOR_NAME') THEN
        ALTER TABLE ST_STOCK_MASTER ADD COLUMN SECTOR_NAME VARCHAR(100) COMMENT '업종명';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ST_STOCK_MASTER' AND COLUMN_NAME = 'PRICE_CHANGE') THEN
        ALTER TABLE ST_STOCK_MASTER ADD COLUMN PRICE_CHANGE VARCHAR(20) COMMENT '전일대비 변동액';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ST_STOCK_MASTER' AND COLUMN_NAME = 'FLUCTUATION_RATE') THEN
        ALTER TABLE ST_STOCK_MASTER ADD COLUMN FLUCTUATION_RATE VARCHAR(20) COMMENT '등락률';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ST_STOCK_MASTER' AND COLUMN_NAME = 'OPEN_PRICE') THEN
        ALTER TABLE ST_STOCK_MASTER ADD COLUMN OPEN_PRICE VARCHAR(20) COMMENT '시가';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ST_STOCK_MASTER' AND COLUMN_NAME = 'HIGH_PRICE') THEN
        ALTER TABLE ST_STOCK_MASTER ADD COLUMN HIGH_PRICE VARCHAR(20) COMMENT '고가';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ST_STOCK_MASTER' AND COLUMN_NAME = 'LOW_PRICE') THEN
        ALTER TABLE ST_STOCK_MASTER ADD COLUMN LOW_PRICE VARCHAR(20) COMMENT '저가';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ST_STOCK_MASTER' AND COLUMN_NAME = 'TRADING_VALUE') THEN
        ALTER TABLE ST_STOCK_MASTER ADD COLUMN TRADING_VALUE VARCHAR(30) COMMENT '거래대금';
    END IF;
END //
DELIMITER ;

CALL add_advstock_columns();
DROP PROCEDURE IF EXISTS add_advstock_columns;
