drop table ST_STOCK_MASTER;

create table ST_STOCK_MASTER(
    ID bigint(20) unsigned NOT NULL COMMENT 'ID',
    CREATE_DATE TIMESTAMP DEFAULT NOW() COMMENT '생성일',
    UPDATE_DATE TIMESTAMP COMMENT '수정일',
    DELETE_YN VARCHAR(1) DEFAULT 'N' COMMENT '삭제여부',
    STOCK_ID  VARCHAR(20) NOT NULL PRIMARY KEY  COMMENT '종목_ID',
	NAME  VARCHAR(50) COMMENT '종목명',
	PRICE  BIGINT(20) unsigned COMMENT '현재가',
	PRICE_BEFOREDAY  BIGINT(20) unsigned COMMENT '전일가',
	FACE_VALUE  BIGINT(10) unsigned COMMENT '액면가',
	MARKET_CAPITALIZATION  BIGINT(20) unsigned COMMENT '시가총액',
	STOCK_QTY  BIGINT(20) unsigned COMMENT '상장주식수',
	FOREIGNER_RATIO  DECIMAL(10,2) unsigned COMMENT '외국인비율',
	VOLUMN  BIGINT(20) unsigned COMMENT '거래량',
	PER  DECIMAL(10,2)  COMMENT 'PER',
	ESTIMATION_PER  DECIMAL(10,2)  COMMENT '추정PER',
	ROE  DECIMAL(10,2)  COMMENT 'ROE',
	PBR  DECIMAL(10,2)  COMMENT 'PBR',
	BPS  DECIMAL(10,2)  COMMENT 'BPS',
	EPS DECIMAL(10,2)  COMMENT 'EPS',
	ESTIMATION_EPS DECIMAL(10,2)  COMMENT '추정EPS',
	INDUSTRY_PER  DECIMAL(10,2)  COMMENT '동일업종 PER',
	INDUSTRY_BAISSE  DECIMAL(10,2)  COMMENT '동일업종 등락률',
	INVESTMENT_OPINION  VARCHAR(10)  COMMENT '투자의견',
	TARGET_PRICE  BIGINT(20) unsigned COMMENT '목표주가',
	MAX_52  BIGINT(20) unsigned COMMENT '52주 최고',
	MIN_52  BIGINT(20) unsigned COMMENT '52주 최저',
	DIVIDEND_RATE  DECIMAL(10,2) unsigned COMMENT '배당수익률',
	NATIONAL  VARCHAR(20) COMMENT '종목 국가' 
)COMMENT='주식 마스터 테이블' ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;


ALTER TABLE ST_STOCK_MASTER DROP PRIMARY key;

ALTER TABLE ST_STOCK_MASTER ADD PRIMARY KEY (ID);

ALTER TABLE ST_STOCK_MASTER ADD UNIQUE STOCK_MASTER_UNIQUE (STOCK_ID);



 create table ST_STOCK_DAILY_PRICE(
    ID bigint(20) unsigned NOT NULL COMMENT 'ID',
    STOCK_ID  VARCHAR(20) COMMENT '종목ID',
 	TRADING_DATE  VARCHAR(20) COMMENT '날짜',
	CLOSING_PRICE  DECIMAL(10, 2) COMMENT '종가',
	PREVIOUS_DAY_RATE  DECIMAL(10, 2) COMMENT '전일비',
	FLUCTUATION_RATE  DECIMAL(10, 2) COMMENT '등락률',
	VOLUMN  DECIMAL(10, 2) COMMENT '거래량',
	ORGAN_TRADING_VOLUMN  DECIMAL(10, 2) COMMENT '기관_매매량',
	FOREIGN_TRADING_VOLUMN  DECIMAL(20, 2) COMMENT '외국인_매매량',
	FOREIGN_HOLDING_VOLUMN  DECIMAL(20, 2) COMMENT '외국인_보유주수',
	FOREIGN_HOLDING_RATE  DECIMAL(10, 2) COMMENT '외국인_보유율',
	PRIMARY KEY(ID),
	UNIQUE (STOCK_ID, TRADING_DATE)
 )COMMENT='주식 DAILY 주가 테이블' ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;
 
 


SELECT AA.INVESTMENT_OPINION, AA.NAME, AA.PER, AA.ROE, AA.PBR, AA.PRICE, AA.TARGET_PRICE, AA.MARKET_CAPITALIZATION AS MARKET, AA.STOCK_QTY,
   AA.FOREIGNER_RATIO AS FOREIGNER, AA.TARGET_PRICE / AA.PRICE AS INCR, AA.*
FROM ST_STOCK_MASTER AA
ORDER BY INCR DESC, INVESTMENT_OPINION DESC;

SELECT RANK()OVER( ORDER BY CAL_PER )+RANK()OVER( ORDER BY CAL_ROE) RANKING,
   RANK()OVER( ORDER BY CAL_PER ) RANK_PER, RANK()OVER( ORDER BY CAL_ROE) RANK_ROE,
   AA.NAME, AA.PER, AA.ROE, AA.PRICE, AA.MARKET_CAPITALIZATION MARKET, AA.TARGET_PRICE, AA.INVESTMENT_OPINION INVESTMET,  AA.*
FROM
(
SELECT CASE WHEN S.PER < 0 THEN ABS(S.PER *10000) WHEN S.PER = 0 THEN 10000 ELSE S.PER END CAL_PER, 
	CASE WHEN S.ROE < 0 THEN ABS(S.ROE *10000) WHEN S.ROE = 0 THEN 10000 ELSE S.ROE END CAL_ROE,   S.*
FROM st_stock_master s
)AA
ORDER BY INVESTMET DESC, RANKING;


create table ST_STOCK_FINANCIAL(
    ID bigint(20) unsigned NOT NULL COMMENT 'ID',
    CREATE_DATE TIMESTAMP DEFAULT NOW() COMMENT '생성일',
    UPDATE_DATE TIMESTAMP COMMENT '수정일',
    DELETE_YN VARCHAR(1) DEFAULT 'N' COMMENT '삭제여부',
    TOTAL_SALES  BIGINT(20) COMMENT '매출액(억원)',
	PROFITS  BIGINT(20) COMMENT '영업이익(억원)',
	EARNINGS  BIGINT(20) COMMENT '당기순이익(억원)',
	PROFITS_RATIO  DECIMAL(10, 2) COMMENT '영업이익률(%)',
	NET_PROFIT_RATIO  DECIMAL(10, 2) COMMENT '순이익률(%)',
	ROE  DECIMAL(10, 2) COMMENT 'ROE(%)',
	DEPT_RATIO DECIMAL(10, 2) COMMENT '부채비율(%)',
	RESERVE_RATIO  DECIMAL(10, 2) COMMENT '유보율(%)',
	EPS  DECIMAL(10, 2) COMMENT 'EPS(원)',
	PER  DECIMAL(10, 2) COMMENT 'PER(배)',
	BPS  DECIMAL(10, 2) COMMENT 'BPS(배)',
	PBR  DECIMAL(10, 2) COMMENT 'PBR(배)',
	DIVIDENDS_PER_SHARE  BIGINT(20) COMMENT '주당배당금(원)',
	DIVIDENDS_RATE  DECIMAL(10, 2) COMMENT '시가배당률(%)',
	DIVIDENDS_TENDENCY  DECIMAL(10, 2) COMMENT '배당성향(%)',
	YEAR  VARCHAR(10) COMMENT '년도',
	STOCK_ID  VARCHAR(20) COMMENT '종목ID',
	STOCK_MASTER_ID  BIGINT(20) COMMENT 'MASTER_ID',
	SHARES_OUTSTANDING  BIGINT(20) COMMENT '발행주식수',
	TOTAL_ASSETS  BIGINT(20) COMMENT '자산총계',
	TOTAL_DEPT  BIGINT(20) COMMENT '부채총계',
	TOTAL_CAPITAL  BIGINT(20) COMMENT '자본총계',
	CAPITAL  BIGINT(20) COMMENT '자본금',
	PRIMARY KEY (ID),
	UNIQUE (STOCK_ID, YEAR)
)COMMENT='주식 재무 테이블' ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;


create table ST_STOCK_INTEREST(
    STOCK_ID  VARCHAR(20) COMMENT '종목_ID',
	NAME  VARCHAR(50) COMMENT '종목명',
	STOCK_TYPE  VARCHAR(50) COMMENT '보유TYPE',
	STOCK_TYPE_DETAIL  VARCHAR(50) COMMENT '보유TYPE상세',
	STOCK_DIVISION  VARCHAR(50) COMMENT '계좌구분',
	STOCK_QTY  INT COMMENT '보유수량',
	STOCK_POTION  DECIMAL(10,4) COMMENT '비중',
	UNIQUE (STOCK_ID, STOCK_DIVISION)
)COMMENT='관심종목 테이블' ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table ST_STOCK_INTEREST_PARAM(
    STOCK_DIVISION  VARCHAR(50) NOT NULL PRIMARY KEY COMMENT '계좌구분',
    STANDARD_PRICE  BIGINT COMMENT '기준금액',
    ORDER_NUM  INT COMMENT '정렬순서'
)COMMENT='관심종목 기준금액 파라미터 테이블' ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 기준금액 초기 데이터
INSERT INTO ST_STOCK_INTEREST_PARAM (STOCK_DIVISION, STANDARD_PRICE, ORDER_NUM) VALUES ('한투 ISA', 150000, 3);
INSERT INTO ST_STOCK_INTEREST_PARAM (STOCK_DIVISION, STANDARD_PRICE, ORDER_NUM) VALUES ('미래에셋 퇴직연금', 1000000, 11);
INSERT INTO ST_STOCK_INTEREST_PARAM (STOCK_DIVISION, STANDARD_PRICE, ORDER_NUM) VALUES ('한투 개인연금', 1080000, 12);
INSERT INTO ST_STOCK_INTEREST_PARAM (STOCK_DIVISION, STANDARD_PRICE, ORDER_NUM) VALUES ('미래에셋 개인연금', 120000, 14);
INSERT INTO ST_STOCK_INTEREST_PARAM (STOCK_DIVISION, STANDARD_PRICE, ORDER_NUM) VALUES ('한투 퇴직연금', 200000, 15);

create table ST_STOCK_CATEGORY(
    ID bigint(20) unsigned NOT NULL COMMENT 'ID',
    CATEGORY_TYPE  VARCHAR(50) COMMENT '업종종류',
    CATEGORY_NO  VARCHAR(50) COMMENT '업종NO',
    CATEGORY_NAME  VARCHAR(50) COMMENT '업종명',
    PRIMARY KEY (ID),
	UNIQUE (CATEGORY_NO)
  )  COMMENT='카테고리 테이블' ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;
 
create table ST_STOCK_CATEGORY_LINK(
    ID bigint(20) unsigned NOT NULL COMMENT 'ID',
    CATEGORY_NO  VARCHAR(50) COMMENT '업종NO',
    STOCK_ID  VARCHAR(20) COMMENT '종목ID',
    PRIMARY KEY(ID),
    UNIQUE (CATEGORY_NO, STOCK_ID)
 )COMMENT='카테고리 LINK 테이블' ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;
 
 
 create table ST_STOCK_ESG(
 	ID bigint(20) unsigned NOT NULL COMMENT 'ID',
 	CREATE_DATE TIMESTAMP DEFAULT NOW() COMMENT '생성일',
    UPDATE_DATE TIMESTAMP COMMENT '수정일',
    DELETE_YN VARCHAR(1) DEFAULT 'N' COMMENT '삭제여부',
 	YEAR  VARCHAR(10) COMMENT '년도',
	STOCK_ID  VARCHAR(20) COMMENT '종목ID',
	GREEN_HOUSE_EMISSION  DECIMAL(10, 2) COMMENT '온실가스 배출량 E02',
	ENERGY_USAGE  DECIMAL(10, 5) COMMENT '에너지 사용량 E03',
	FINE_DUST_USAGE  DECIMAL(10, 5) COMMENT '미세먼지 배출량 E05',
	WATER_RECYCLING_RATE  DECIMAL(10, 5) COMMENT '용수 재활용률 E01',
	WASTE_RECYCLING_RATE  DECIMAL(10, 5) COMMENT '폐기물 재활용률 E04',
	AVERAGE_ANNUAL_SALARY  DECIMAL(10, 5) COMMENT '직원 평균 연봉 S05',
	NON_REGULAR_EMPLYMENT_RATE  DECIMAL(10, 5) COMMENT '비정규직 고용률 S04',
	DONATION  DECIMAL(10, 5) COMMENT '기부금 S01',
	CONTINUOUS_SERVICE_YEAR  DECIMAL(10, 5) COMMENT '직원 평균 근속년수 S02',
	OUTSIDE_DIRECTOR_RATE  DECIMAL(10, 5) COMMENT '사외이사 비율 G03',
	LARGEST_SHARE_HOLDER_RATIO DECIMAL(10, 5) COMMENT '최대주주 지분율 G05',
	DIRECTORATE_INDEPENDENCE DECIMAL(10, 5) COMMENT '이사회의 독립성  G04',
	EXECUTIVE_AVERAGE_ANNUAL_SALARY DECIMAL(10, 5) COMMENT '사내등기임원 평균 보수 G01',
	SALARY_RATIO DECIMAL(10, 5) COMMENT '임원/직원 보수 비율 G02',
 	PRIMARY KEY(ID),
 	UNIQUE (STOCK_ID, YEAR)
 )COMMENT='STOCK ESG 테이블' ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;
 
  create table ST_STOCK_MARKET_INDEX(
 	ID bigint(20) unsigned NOT NULL COMMENT 'ID',
 	CREATE_DATE TIMESTAMP DEFAULT NOW() COMMENT '생성일',
    UPDATE_DATE TIMESTAMP COMMENT '수정일',
    DELETE_YN VARCHAR(1) DEFAULT 'N' COMMENT '삭제여부',
 	YYYYMMDD  VARCHAR(10) COMMENT '년월일',
	DOMESTIC_INTEREST_CALL  DECIMAL(10, 2) COMMENT '콜금리 (1일)',
	DOMESTIC_INTEREST_CD  DECIMAL(10, 5) COMMENT 'CD금리 (91일)',
	DOMESTIC_INTEREST_COFIX_MANF  DECIMAL(10, 5) COMMENT 'COFIX 신규취급액',
	DOMESTIC_INTEREST_COFIX_OUTB  DECIMAL(10, 5) COMMENT 'COFIX 잔액',
	DOMESTIC_INTEREST_NCOFIX_OUTB  DECIMAL(10, 5) COMMENT 'COFIX 신잔액',
	STANDARD_INTEREST_US  DECIMAL(10, 5) COMMENT '미국연방준비은행',
	STANDARD_INTEREST_KR  DECIMAL(10, 5) COMMENT '한국은행',
	STANDARD_INTEREST_EU  DECIMAL(10, 5) COMMENT '유럽중앙은행',
	STANDARD_INTEREST_GB  DECIMAL(10, 5) COMMENT '영국은행',
	STANDARD_INTEREST_JP  DECIMAL(10, 5) COMMENT '일본은행',
	METAL_GC DECIMAL(10, 5) COMMENT '국제 금',
	METAL_CMDT DECIMAL(10, 5) COMMENT '국내 금',
	METAL_SI DECIMAL(10, 5) COMMENT '은',
	METAL_HG DECIMAL(10, 5) COMMENT '구리(선물)',
	METAL_PL  DECIMAL(10, 2) COMMENT '백금',
	TRANSPORT_CCF  DECIMAL(10, 5) COMMENT '중국컨테이너 운임지수',
	TRANSPORT_SCF  DECIMAL(10, 5) COMMENT '상하이컨테이너 운임지수',
	TRANSPORT_BADI  DECIMAL(10, 5) COMMENT 'BDI 건화물선지수',
	TRANSPORT_BACK  DECIMAL(10, 5) COMMENT 'BCI 케이프사이즈지수',
	TRANSPORT_BPNI  DECIMAL(10, 5) COMMENT 'BPI 파나막스지수',
	TRANSPORT_BSIS  DECIMAL(10, 5) COMMENT 'BSI 수프라막스지수',
	TRANSPORT_BHSI  DECIMAL(10, 5) COMMENT 'BHI 핸디사이즈지수',
	TRANSPORT_BAID  DECIMAL(10, 5) COMMENT 'BDTI 원유유조선지수',
	TRANSPORT_BAIT  DECIMAL(10, 5) COMMENT 'BCTI 석유제품선지수',
	BOND_US10YT DECIMAL(10, 5) COMMENT '미국 국채 10년',
	BOND_KR10YT DECIMAL(10, 5) COMMENT '한국 국채 10년',
	BOND_JP10YT DECIMAL(10, 5) COMMENT '일본 국채 10년',
	BOND_DE10YT DECIMAL(10, 5) COMMENT '독일 국채 10년',
	BOND_CN10YT  DECIMAL(10, 5) COMMENT '중국 국채 10년',
	ENERGY_CL  DECIMAL(10, 5) COMMENT 'WTI',
	ENERGY_LCO DECIMAL(10, 5) COMMENT '브렌트유',
	ENERGY_RB DECIMAL(10, 5) COMMENT 'RBOB 가솔린',
	ENERGY_HO DECIMAL(10, 5) COMMENT '난방유',
	ENERGY_DCB DECIMAL(10, 5) COMMENT '두바이유',
 	PRIMARY KEY(ID),
 	UNIQUE (YYYYMMDD)
 )COMMENT='STOCK MARKET INDEX 테이블' ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;
